# Generated by Django 2.2.12 on 2020-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(max_length=10)),
                ('begin', models.DateTimeField(verbose_name='data of beginning class')),
                ('end', models.DateTimeField(verbose_name='data of ending class')),
            ],
        ),
    ]
