# Generated by Django 3.0.5 on 2020-05-12 19:54


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10, unique=True)),
                ('class_size', models.IntegerField(default=30)),
                ('class_type', models.CharField(choices=[('lecture', 'lecture hall'), ('computers', 'classroom with computers'), ('board', 'normal class with board only')], default='board', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='time class start (for now assuming that class duration is 1.5h)')),
                ('time_end', models.TimeField(verbose_name='time class ends')),
                ('is_regular', models.BooleanField(default=True, verbose_name="If it's regular classes. Default to regular classes.")),
                ('is_AB', models.BooleanField(verbose_name="If it's A/B classes.")),
                ('reserved_by', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer')], max_length=6)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationService.ClassName')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reservation date')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationService.ClassroomReservation')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomReservationAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now=True, verbose_name='Reservation date')),
                ('time_start', models.TimeField(verbose_name='time class start (for now assuming that class duration is 1.5h)')),
                ('time_end', models.TimeField(verbose_name='time class ends')),
                ('reserved_by', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer')], max_length=6)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationService.ClassName')),
            ],
        ),
        migrations.AddConstraint(
            model_name='classroomreservation',
            constraint=models.CheckConstraint(check=models.Q(semester__in=['winter', 'summer']), name='reservationservice_classroomreservation_semester_valid'),
        ),
    ]
