# Generated by Django 3.0.5 on 2020-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomreservation',
            name='is_regular',
            field=models.BooleanField(default=True, verbose_name="If it's regular classes. Default to regular classes."),
        ),
    ]
