# Generated by Django 3.0.5 on 2020-04-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0002_auto_20200423_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomreservation',
            name='semester',
            field=models.CharField(choices=[('winter', 'winter'), ('summer', 'summer')], max_length=6),
        ),
        migrations.AddConstraint(
            model_name='classroomreservation',
            constraint=models.CheckConstraint(check=models.Q(semester__in=['winter', 'summer']), name='reservationservice_classroomreservation_status_valid'),
        ),
    ]
