# Generated by Django 3.0.5 on 2020-05-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0002_classname_class_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='class_type',
            field=models.CharField(choices=[('lecture', 'lecture hall'), ('computers', 'classroom with computers'), ('board', 'normal class with board only')], default='board', max_length=10),
        ),
    ]
