# Generated by Django 3.0.5 on 2020-05-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0003_classname_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='class_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ClassroomReservationAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='Reservation date')),
                ('time_start', models.TimeField(verbose_name='time class start (for now assuming that class duration is 1.5h)')),
                ('time_end', models.TimeField(verbose_name='time class ends')),
                ('reserved_by', models.CharField(blank=True, max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer')], max_length=6)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationService.ClassName')),
            ],
        ),
    ]
