# Generated by Django 3.0.5 on 2020-04-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0003_auto_20200424_0138'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroomreservation',
            name='reservationservice_classroomreservation_status_valid',
        ),
    ]
