# Generated by Django 3.0.5 on 2020-05-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0004_auto_20200505_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomreservationattempts',
            name='reservation_date',
            field=models.DateField(auto_now=True, verbose_name='Reservation date'),
        ),
    ]
