# Generated by Django 3.0.5 on 2020-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationService', '0005_auto_20200424_0140'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classroomreservation',
            name='reservationservice_classroomreservation_status_valid',
        ),
        migrations.AddConstraint(
            model_name='classroomreservation',
            constraint=models.CheckConstraint(check=models.Q(semester__in=['winter', 'summer']), name='reservationservice_classroomreservation_semester_valid'),
        ),
    ]
